### ISSUE TITLE
Запросы, выражения?

### ISSUE THREAD

**Issue by pepelsbey** [FrontenderMagazine/svg-media-queries#2]
На главной сайта: _SVG и медиавыражения_
На странице статьи: _SVG и медиа-запросы_

Это как?

1. Медиа- пишется слитно со словом, поэтому медиавыражения, медиазапросы.
2. Откуда вообще взялись два термина запросы и выражения? Я сломался, когда фразу прочитал:

> Использовать медиа-запросы для реализации медиа-выражений

Это как вообще? В оригинале всё просто, без рекурсии:

> Use media queries to add responsiveness

Моё предложение: назвать всё медиавыражениями, поскольку это не SQL и никаких запросов никуда не уходит. Идёт проверка выражений и применяются стили. Это всё не с потолка, у нас есть подробный [перевод всех частей медиавыражений в словаре](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#media-query).

**Comment by vkabysh** [comment]
Добрый вечер, Вы правы!
Приношу свои извинения. 
Сейчас внесу корректировки.

**Comment by Marat-Tanalin** [comment]
> это не SQL и никаких запросов никуда не уходит.

Запрос к браузеру на предмет соответствия условия действительности.
